apiVersion: apps/v1
kind: Deployment
metadata:
  name: q12
  labels:
    app: q12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: q12
  template:
    metadata:
      labels:
        app: q12
    spec:
      containers:
      - name: q12
        image: dukezheng0726/finalexam:latest
        ports:
        - containerPort: 8080